# Generated by Django 5.1.1 on 2024-09-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.odontologo')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('nombre_apellido_contacto_emergencia', models.CharField(max_length=150)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('parentesco_contacto_emergencia', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_consulta', models.TextField()),
                ('disponibilidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.disponibilidad')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.pacientes')),
            ],
        ),
    ]
